"""description

Revision ID: 47cc29ee2ba8
Revises: 70f1b241413b
Create Date: 2026-02-23 15:53:14.017934

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "47cc29ee2ba8"
down_revision: Union[str, Sequence[str], None] = "70f1b241413b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Explicitly create the new ENUM type
    sa.Enum(
        "LOGIN", "INITIAL_VERIFICATION", "PASSWORD_RESET", name="verification_type_enum"
    ).create(op.get_bind())

    op.alter_column(
        "verification_tokens",
        "token_type",
        existing_type=postgresql.ENUM(
            "ACCESS",
            "REFRESH",
            "EMAIL_VERIFICATION",
            "PASSWORD_RESET",
            name="token_type_enum",
        ),
        type_=sa.Enum(
            "LOGIN",
            "INITIAL_VERIFICATION",
            "PASSWORD_RESET",
            name="verification_type_enum",
        ),
        existing_nullable=False,
        postgresql_using="token_type::text::verification_type_enum",
    )

    # Explicitly drop the old ENUM type
    sa.Enum(name="token_type_enum").drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum(
        "ACCESS",
        "REFRESH",
        "EMAIL_VERIFICATION",
        "PASSWORD_RESET",
        name="token_type_enum",
    ).create(op.get_bind())

    op.alter_column(
        "verification_tokens",
        "token_type",
        existing_type=sa.Enum(
            "LOGIN",
            "INITIAL_VERIFICATION",
            "PASSWORD_RESET",
            name="verification_type_enum",
        ),
        type_=postgresql.ENUM(
            "ACCESS",
            "REFRESH",
            "EMAIL_VERIFICATION",
            "PASSWORD_RESET",
            name="token_type_enum",
        ),
        existing_nullable=False,
        postgresql_using="token_type::text::token_type_enum",
    )

    sa.Enum(name="verification_type_enum").drop(op.get_bind())
    # ### end Alembic commands ###
