"""description

Revision ID: 772323349127
Revises: c83e9a328da5
Create Date: 2026-02-23 14:50:41.367370

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "772323349127"
down_revision: Union[str, Sequence[str], None] = "c83e9a328da5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
