"""add_claims_management_system

Revision ID: b2ca32d08927
Revises: 47cc29ee2ba8
Create Date: 2026-02-23 21:14:24.095244

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b2ca32d08927"
down_revision: Union[str, Sequence[str], None] = "47cc29ee2ba8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "diagnoses",
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_table(
        "members",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("phone_number", sa.String(length=20), nullable=True),
        sa.Column(
            "status",
            sa.Enum("active", "inactive", "suspended", name="member_status_enum"),
            server_default="active",
            nullable=False,
        ),
        sa.Column("benefit_limit", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("used_benefit", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_members_email"), "members", ["email"], unique=False)
    op.create_table(
        "procedures",
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("average_cost", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_table(
        "providers",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("address", sa.String(length=500), nullable=True),
        sa.Column("phone_number", sa.String(length=20), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "claims",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("member_id", sa.String(length=50), nullable=False),
        sa.Column("provider_id", sa.String(length=50), nullable=False),
        sa.Column("diagnosis_code", sa.String(length=50), nullable=False),
        sa.Column("procedure_code", sa.String(length=50), nullable=False),
        sa.Column("claim_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("approved_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "approved", "partial", "rejected", name="claim_status_enum"
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("fraud_flag", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("fraud_reason", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["diagnosis_code"],
            ["diagnoses.code"],
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.ForeignKeyConstraint(
            ["procedure_code"],
            ["procedures.code"],
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_claims_created_at"), "claims", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_claims_member_id"), "claims", ["member_id"], unique=False)
    op.create_index(
        op.f("ix_claims_provider_id"), "claims", ["provider_id"], unique=False
    )
    op.create_index(op.f("ix_claims_status"), "claims", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_claims_status"), table_name="claims")
    op.drop_index(op.f("ix_claims_provider_id"), table_name="claims")
    op.drop_index(op.f("ix_claims_member_id"), table_name="claims")
    op.drop_index(op.f("ix_claims_created_at"), table_name="claims")
    op.drop_table("claims")
    op.drop_table("providers")
    op.drop_table("procedures")
    op.drop_index(op.f("ix_members_email"), table_name="members")
    op.drop_table("members")
    op.drop_table("diagnoses")
    # ### end Alembic commands ###
