"""description

Revision ID: c83e9a328da5
Revises: 02a23ab579d8
Create Date: 2026-02-23 14:50:07.381815

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "c83e9a328da5"
down_revision: Union[str, Sequence[str], None] = "02a23ab579d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
